name: trakt_dart
description: A Dart client-side API package for the Trakt.tv API, a database on what tv shows and movies everyone is watching.
version: 1.0.0
repository: https://github.com/nikkithomas2012/trakt_dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.1.5
  dotenv: ^3.0.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  source_gen: ^1.1.0

flutter:

assets:
  - .env
