name: trakt_dart
description: A Dart client-side API package for the Trakt.tv API, a database on what tv shows and movies everyone is watching.
version: 1.0.1
repository: https://github.com/nikkithomas2012/trakt_dart

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  build_runner: ^2.4.6
  dotenv: ^4.1.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  source_gen: ^1.4.0

flutter:

assets:
  - .env
